from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


OUTPUT_DIR = Path("outputs/plots")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def plot_voltage_vs_time(data: pd.DataFrame) -> None:
    plt.figure(figsize=(12, 6))

    plt.plot(
        data["Time(s)"],
        data["Voltage(V)"],
        linewidth=2.5,
        marker="o",
        markersize=5,
    )

    plt.title(
        "Battery Voltage vs Time",
        fontsize=16,
        fontweight="bold",
    )

    plt.xlabel("Time (s)", fontsize=12)
    plt.ylabel("Voltage (V)", fontsize=12)

    plt.tick_params(labelsize=11)

    plt.grid(
        True,
        linestyle="--",
        alpha=0.6,
    )

    plt.tight_layout()

    plt.savefig(
        OUTPUT_DIR / "voltage_vs_time.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()


def plot_soc_vs_time(data: pd.DataFrame) -> None:
    plt.figure(figsize=(12, 6))

    plt.plot(
        data["Time(s)"],
        data["SoC(%)"],
        linewidth=2.5,
        marker="o",
        markersize=5,
        color="tab:green",
    )

    plt.title(
        "Battery State of Charge vs Time",
        fontsize=16,
        fontweight="bold",
    )

    plt.xlabel("Time (s)", fontsize=12)
    plt.ylabel("State of Charge (%)", fontsize=12)

    plt.tick_params(labelsize=11)

    plt.grid(
        True,
        linestyle="--",
        alpha=0.6,
    )

    plt.tight_layout()

    plt.savefig(
        OUTPUT_DIR / "soc_vs_time.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()


def plot_dashboard(data: pd.DataFrame) -> None:
    fig, axes = plt.subplots(
        2,
        1,
        figsize=(12, 10),
    )

    # Voltage Plot
    axes[0].plot(
        data["Time(s)"],
        data["Voltage(V)"],
        linewidth=2.5,
        marker="o",
        markersize=5,
    )

    axes[0].set_title(
        "Battery Voltage vs Time",
        fontsize=14,
        fontweight="bold",
    )

    axes[0].set_xlabel("Time (s)", fontsize=11)
    axes[0].set_ylabel("Voltage (V)", fontsize=11)

    axes[0].tick_params(labelsize=10)

    axes[0].grid(
        True,
        linestyle="--",
        alpha=0.6,
    )

    # SoC Plot
    axes[1].plot(
        data["Time(s)"],
        data["SoC(%)"],
        linewidth=2.5,
        marker="o",
        markersize=5,
        color="tab:green",
    )

    axes[1].set_title(
        "Battery State of Charge vs Time",
        fontsize=14,
        fontweight="bold",
    )

    axes[1].set_xlabel("Time (s)", fontsize=11)
    axes[1].set_ylabel("State of Charge (%)", fontsize=11)

    axes[1].tick_params(labelsize=10)

    axes[1].grid(
        True,
        linestyle="--",
        alpha=0.6,
    )

    fig.suptitle(
        "Battery Analysis Dashboard",
        fontsize=20,
        fontweight="bold",
    )

    fig.text(
    0.5,
    0.01,
    "Generated by Battery SoC Estimator",
    ha="center",
    fontsize=10,
    style="italic",
    )   

    fig.tight_layout(rect=[0.02, 0.03, 0.98, 0.95])

    plt.savefig(
        OUTPUT_DIR / "battery_analysis_dashboard.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)